In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn import svm
from sklearn.metrics import accuracy_score

In [2]:
# loading the diabetes dataset to a pandas DataFrame
diabetes_dataset = pd.read_csv('diabetes_data.csv')

In [3]:
# printing the first 5 rows of the dataset
diabetes_dataset.head()

,Diabetes_012,HighBP,HighChol,CholCheck,BMI,Smoker,Stroke,HeartDiseaseorAttack,PhysActivity,Fruits,...,AnyHealthcare,NoDocbcCost,GenHlth,MentHlth,PhysHlth,DiffWalk,Sex,Age,Education,Income
0,0.0,1.0,1.0,1.0,40.0,1.0,0.0,0.0,0.0,0.0,...,1.0,0.0,5.0,18.0,15.0,1.0,0.0,9.0,4.0,3.0
1,0.0,0.0,0.0,0.0,25.0,1.0,0.0,0.0,1.0,0.0,...,0.0,1.0,3.0,0.0,0.0,0.0,0.0,7.0,6.0,1.0
2,0.0,1.0,1.0,1.0,28.0,0.0,0.0,0.0,0.0,1.0,...,1.0,1.0,5.0,30.0,30.0,1.0,0.0,9.0,4.0,8.0
3,0.0,1.0,0.0,1.0,27.0,0.0,0.0,0.0,1.0,1.0,...,1.0,0.0,2.0,0.0,0.0,0.0,0.0,11.0,3.0,6.0
4,0.0,1.0,1.0,1.0,24.0,0.0,0.0,0.0,1.0,1.0,...,1.0,0.0,2.0,3.0,0.0,0.0,0.0,11.0,5.0,4.0

In [4]:
# number of rows and Columns in this dataset
diabetes_dataset.shape

(253680, 22)

In [5]:
# getting the statistical measures of the data
diabetes_dataset.describe()

,Diabetes_012,HighBP,HighChol,CholCheck,BMI,Smoker,Stroke,HeartDiseaseorAttack,PhysActivity,Fruits,...,AnyHealthcare,NoDocbcCost,GenHlth,MentHlth,PhysHlth,DiffWalk,Sex,Age,Education,Income
count,253680.000000,253680.000000,253680.000000,253680.000000,253680.000000,253680.000000,253680.000000,253680.000000,253680.000000,253680.000000,...,253680.000000,253680.000000,253680.000000,253680.000000,253680.000000,253680.000000,253680.000000,253680.000000,253680.000000,253680.000000
mean,0.296921,0.429001,0.424121,0.962670,28.382364,0.443169,0.040571,0.094186,0.756544,0.634256,...,0.951053,0.084177,2.511392,3.184772,4.242081,0.168224,0.440342,8.032119,5.050434,6.053875
std,0.698160,0.494934,0.494210,0.189571,6.608694,0.496761,0.197294,0.292087,0.429169,0.481639,...,0.215759,0.277654,1.068477,7.412847,8.717951,0.374066,0.496429,3.054220,0.985774,2.071148
min,0.000000,0.000000,0.000000,0.000000,12.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000,1.000000
25%,0.000000,0.000000,0.000000,1.000000,24.000000,0.000000,0.000000,0.000000,1.000000,0.000000,...,1.000000,0.000000,2.000000,0.000000,0.000000,0.000000,0.000000,6.000000,4.000000,5.000000
50%,0.000000,0.000000,0.000000,1.000000,27.000000,0.000000,0.000000,0.000000,1.000000,1.000000,...,1.000000,0.000000,2.000000,0.000000,0.000000,0.000000,0.000000,8.000000,5.000000,7.000000
75%,0.000000,1.000000,1.000000,1.000000,31.000000,1.000000,0.000000,0.000000,1.000000,1.000000,...,1.000000,0.000000,3.000000,2.000000,3.000000,0.000000,1.000000,10.000000,6.000000,8.000000
max,2.000000,1.000000,1.000000,1.000000,98.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,5.000000,30.000000,30.000000,1.000000,1.000000,13.000000,6.000000,8.000000

In [7]:
diabetes_dataset['Diabetes_012'].value_counts()

0.0    213703
2.0     35346
1.0      4631
Name: Diabetes_012, dtype: int64

In [8]:
diabetes_dataset.groupby('Diabetes_012').mean()

,HighBP,HighChol,CholCheck,BMI,Smoker,Stroke,HeartDiseaseorAttack,PhysActivity,Fruits,Veggies,...,AnyHealthcare,NoDocbcCost,GenHlth,MentHlth,PhysHlth,DiffWalk,Sex,Age,Education,Income
Diabetes_012,,,,,,,,,,,,,,,,,,,,,
0.0,0.371132,0.379171,0.957104,27.742521,0.429680,0.031628,0.071833,0.779077,0.643023,0.821439,...,0.949739,0.079610,2.372391,2.944404,3.582416,0.132282,0.433985,7.786559,5.106629,6.208663
1.0,0.629022,0.620816,0.986612,30.724466,0.492766,0.057223,0.143382,0.678471,0.602246,0.768948,...,0.945152,0.129346,2.975599,4.529907,6.348305,0.277478,0.437702,9.083351,4.784496,5.351112
2.0,0.752674,0.670118,0.993182,31.944011,0.518220,0.092457,0.222882,0.630538,0.585441,0.756408,...,0.959769,0.105868,3.290981,4.461806,7.954479,0.371216,0.479121,9.379053,4.745516,5.210094

In [10]:
# separating the data and labels
X = diabetes_dataset.drop(columns = 'Diabetes_012', axis=1)
Y = diabetes_dataset['Diabetes_012']

In [11]:
print(X)

        HighBP  HighChol  CholCheck   BMI  Smoker  Stroke  \
0          1.0       1.0        1.0  40.0     1.0     0.0
1          0.0       0.0        0.0  25.0     1.0     0.0
2          1.0       1.0        1.0  28.0     0.0     0.0
3          1.0       0.0        1.0  27.0     0.0     0.0
4          1.0       1.0        1.0  24.0     0.0     0.0
...        ...       ...        ...   ...     ...     ...
253675     1.0       1.0        1.0  45.0     0.0     0.0
253676     1.0       1.0        1.0  18.0     0.0     0.0
253677     0.0       0.0        1.0  28.0     0.0     0.0
253678     1.0       0.0        1.0  23.0     0.0     0.0
253679     1.0       1.0        1.0  25.0     0.0     0.0

        HeartDiseaseorAttack  PhysActivity  Fruits  Veggies  ...  \
0                        0.0           0.0     0.0      1.0  ...
1                        0.0           1.0     0.0      0.0  ...
2                        0.0           0.0     1.0      0.0  ...
3                        0.0           1.0     1.0      1.0  ...
4                        0.0           1.0     1.0      1.0  ...
...                      ...           ...     ...      ...  ...
253675                   0.0           0.0     1.0      1.0  ...
253676                   0.0           0.0     0.0      0.0  ...
253677                   0.0           1.0     1.0      0.0  ...
253678                   0.0           0.0     1.0      1.0  ...
253679                   1.0           1.0     1.0      0.0  ...

        AnyHealthcare  NoDocbcCost  GenHlth  MentHlth  PhysHlth  DiffWalk  \
0                 1.0          0.0      5.0      18.0      15.0       1.0
1                 0.0          1.0      3.0       0.0       0.0       0.0
2                 1.0          1.0      5.0      30.0      30.0       1.0
3                 1.0          0.0      2.0       0.0       0.0       0.0
4                 1.0          0.0      2.0       3.0       0.0       0.0
...               ...          ...      ...       ...       ...       ...
253675            1.0          0.0      3.0       0.0       5.0       0.0
253676            1.0          0.0      4.0       0.0       0.0       1.0
253677            1.0          0.0      1.0       0.0       0.0       0.0
253678            1.0          0.0      3.0       0.0       0.0       0.0
253679            1.0          0.0      2.0       0.0       0.0       0.0

        Sex   Age  Education  Income
0       0.0   9.0        4.0     3.0
1       0.0   7.0        6.0     1.0
2       0.0   9.0        4.0     8.0
3       0.0  11.0        3.0     6.0
4       0.0  11.0        5.0     4.0
...     ...   ...        ...     ...
253675  1.0   5.0        6.0     7.0
253676  0.0  11.0        2.0     4.0
253677  0.0   2.0        5.0     2.0
253678  1.0   7.0        5.0     1.0
253679  0.0   9.0        6.0     2.0

[253680 rows x 21 columns]

In [12]:
print(Y)

0         0.0
1         0.0
2         0.0
3         0.0
4         0.0
         ...
253675    0.0
253676    2.0
253677    0.0
253678    0.0
253679    2.0
Name: Diabetes_012, Length: 253680, dtype: float64

In [13]:
X_train, X_test, Y_train, Y_test = train_test_split(X,Y, test_size = 0.2, stratify=Y, random_state=2)

In [14]:
print(X.shape, X_train.shape, X_test.shape)

(253680, 21) (202944, 21) (50736, 21)

In [15]:
classifier = svm.SVC(kernel='linear')

In [16]:
#training the support vector Machine Classifier
classifier.fit(X_train, Y_train)

SVC(kernel='linear')

In [17]:
# accuracy score on the training data
X_train_prediction = classifier.predict(X_train)
training_data_accuracy = accuracy_score(X_train_prediction, Y_train)

In [18]:
print('Accuracy score of the training data : ', training_data_accuracy)

Accuracy score of the training data :  0.8424097287921791

In [19]:
# accuracy score on the test data
X_test_prediction = classifier.predict(X_test)
test_data_accuracy = accuracy_score(X_test_prediction, Y_test)

In [20]:
print('Accuracy score of the test data : ', test_data_accuracy)

Accuracy score of the test data :  0.8424195837275308

In [21]:
input_data = (1,1,1,30,1,0,1,0,1,1,0,1,0,5,30,30,1,0,9,5,1)

# changing the input_data to numpy array
input_data_as_numpy_array = np.asarray(input_data)

# reshape the array as we are predicting for one instance
input_data_reshaped = input_data_as_numpy_array.reshape(1,-1)

prediction = classifier.predict(input_data_reshaped)
print(prediction)

if (prediction[0] == 0):
  print('The person is not diabetic')
else:
  print('The person is diabetic')

[0.]
The person is not diabetic

C:\Users\Others\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but SVC was fitted with feature names
  warnings.warn(

In [22]:
import pickle

In [23]:
filename = 'diabetes_model.sav'
pickle.dump(classifier, open(filename, 'wb'))

In [24]:
# loading the saved model
loaded_model = pickle.load(open('diabetes_model.sav', 'rb'))

In [25]:
input_data = (1,1,1,30,1,0,1,0,1,1,0,1,0,5,30,30,1,0,9,5,1)

# changing the input_data to numpy array
input_data_as_numpy_array = np.asarray(input_data)

# reshape the array as we are predicting for one instance
input_data_reshaped = input_data_as_numpy_array.reshape(1,-1)

prediction = loaded_model.predict(input_data_reshaped)
print(prediction)

if (prediction[0] == 0):
  print('The person is not diabetic')
else:
  print('The person is diabetic')

[0.]
The person is not diabetic

C:\Users\Others\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but SVC was fitted with feature names
  warnings.warn(

In [26]:
for column in X.columns:
  print(column)

HighBP
HighChol
CholCheck
BMI
Smoker
Stroke
HeartDiseaseorAttack
PhysActivity
Fruits
Veggies
HvyAlcoholConsump
AnyHealthcare
NoDocbcCost
GenHlth
MentHlth
PhysHlth
DiffWalk
Sex
Age
Education
Income